version: '2'
services:
    kodrisdeveloper-app:
        image: kodrisdeveloper
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://kodrisdeveloper-postgresql:5432/KodrisDeveloper
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    kodrisdeveloper-postgresql:
        extends:
            file: postgresql.yml
            service: kodrisdeveloper-postgresql
