version: '2'
services:
    kodrisdeveloper-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/KodrisDeveloper/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=KodrisDeveloper
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
